"""
# Evermodel Ops
# Copyright (c) OpenSpug Organization. <spug.dev@gmail.com>
# Released under the AGPL-3.0 License.

Django settings for evermodel_ops project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 生产环境请通过环境变量 EVERMODEL_SECRET_KEY 注入；未设置时回退到下面这个
# 仅供本地开发的默认值（同时公开在仓库里，绝不可用于生产）。
SECRET_KEY = os.environ.get('EVERMODEL_SECRET_KEY', 'dev-only-insecure-key-change-in-production')

DEBUG = os.environ.get('EVERMODEL_DEBUG', 'false').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = os.environ.get('EVERMODEL_ALLOWED_HOSTS', '127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'daphne',  # channels 4 起 runserver 的 WebSocket 支持由 daphne 提供，需放在最前
    'apps.account',
    'apps.host',
    'apps.setting',
    'apps.exec',
    'apps.schedule',
    'apps.monitor',
    'apps.alarm',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
    'libs.middleware.TranslateMiddleware',
    'libs.middleware.AuthenticationMiddleware',
    'libs.middleware.HandleExceptionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'evermodel_ops.urls'

WSGI_APPLICATION = 'evermodel_ops.wsgi.application'
ASGI_APPLICATION = 'evermodel_ops.asgi.application'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Database
# 默认连接 MySQL（与 deploy/docker-compose.yaml 一致）。仅本地调试需要 SQLite 时，
# 设置 EVERMODEL_USE_SQLITE=1，并通过 EVERMODEL_MYSQL_* 指定连接信息。
if os.environ.get('EVERMODEL_USE_SQLITE') == '1':
    DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': BASE_DIR / 'db.sqlite3'}}
else:
    DATABASES = {'default': {
        'ATOMIC_REQUESTS': True,
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('EVERMODEL_MYSQL_DB', 'evermodel_ops'),
        'USER': os.environ.get('EVERMODEL_MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('EVERMODEL_MYSQL_PASSWORD', 'evermodel_ops'),
        'HOST': os.environ.get('EVERMODEL_MYSQL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('EVERMODEL_MYSQL_PORT', '3306'),
        'OPTIONS': {'charset': 'utf8mb4', 'sql_mode': 'STRICT_TRANS_TABLES'},
    }}

REDIS_HOST = os.environ.get('EVERMODEL_REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.environ.get('EVERMODEL_REDIS_PORT', '6379'))
REDIS_POOL_KWARGS = {'socket_timeout': None, 'socket_connect_timeout': 10}

CACHES = {'default': {
    'BACKEND': 'django_redis.cache.RedisCache',
    'LOCATION': f'redis://{REDIS_HOST}:{REDIS_PORT}/1',
    'KEY_PREFIX': 'evermodel_ops',
    'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'CONNECTION_POOL_KWARGS': dict(REDIS_POOL_KWARGS)},
}}

CHANNEL_LAYERS = {'default': {
    'BACKEND': 'channels_redis.core.RedisChannelLayer',
    'CONFIG': {'hosts': [dict(host=REDIS_HOST, port=REDIS_PORT, **REDIS_POOL_KWARGS)],
               'prefix': 'evermodel_ops:channel', 'capacity': 1000, 'expiry': 120},
}}

TOKEN_TTL = 8 * 3600
SCHEDULE_KEY = 'evermodel_ops:schedule'
SCHEDULE_WORKER_KEY = 'evermodel_ops:schedule:worker'
MONITOR_KEY = 'evermodel_ops:monitor'
MONITOR_WORKER_KEY = 'evermodel_ops:monitor:worker'
EXEC_WORKER_KEY = 'evermodel_ops:exec:worker'
TRANSFER_DIR = str(BASE_DIR / 'storage' / 'transfer')
REPOS_DIR = str(BASE_DIR.parent.parent / 'repos')
BUILD_DIR = os.path.join(REPOS_DIR, 'build')

# ---------------------------------------------------------------------------
# Grafana 监控大屏：把外部 Grafana 的看板以 iframe 方式嵌进后台（/grafana 页面）
#
# GRAFANA_URL        Grafana 站点根地址，不带结尾斜杠；留空则页面提示去配置
# GRAFANA_DASHBOARDS 看板白名单，元素为 {'uid': ..., 'title': ...} 或纯 uid 字符串；
#                    留空 = 自动从 Grafana /api/search 拉取全部看板
# GRAFANA_TIMEOUT    后端探测 Grafana 的超时时间（秒）
# ---------------------------------------------------------------------------
GRAFANA_URL = ''
GRAFANA_DASHBOARDS = ()
GRAFANA_TIMEOUT = 5

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

AUTHENTICATION_EXCLUDES = (
    '/account/login/',
    '/setting/basic/',
)

EVERMODEL_VERSION = 'v4.0.1'

# override default config
try:
    from evermodel_ops.overrides import *
except ImportError:
    pass
